package com.example.wvdrawercontainer.demo.list


val TEST_DATA = listOf(
    "Apple",
    "Banana",
    "Orange",
    "Watermelon",
    "Grape",
    "Strawberry",
    "Mango",
    "Pineapple",
    "Peach",
    "Pear",
    "Cherry",
    "Lemon",
    "Lime",
    "Coconut",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Kiwi",
    "Papaya",
    "Avocado",
    "Tomato",
    "Potato",
    "Carrot",
    "Onion",
    "Garlic",
    "Cucumber",
    "Broccoli",
    "Spinach",
    "Corn",
    "Pumpkin",
    "Beef",
    "Chicken",
    "Pork",
    "Fish",
    "Shrimp",
    "Rice",
    "Bread",
    "Noodles",
    "Pasta",
    "Pizza",
    "Hamburger",
    "Sandwich",
    "Cake",
    "Cookie",
    "Chocolate",
    "Ice Cream",
    "Coffee",
    "Tea",
    "Milk",
    "Juice"
)